### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by ousamabenyounes** [grabasz/LuxmedRunner#1]
Hi @grabasz 

Your gmail credential are visible here: https://github.com/grabasz/LuxmedRunner/blob/9201b3b50b4841c0935207c20824cdff837590b7/config.ini

to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...

**Comment by grabasz** [comment]
Thank you for your comment!
I am surprised that I did such silly mistake... 
Thanks Heavens that it wasn't my Gmail password!

**Comment by ousamabenyounes** [comment]
Every human do mistakes :)...
And Happy to see that this issue helped you.

It is a pleasure to help other developpers on github
